# Generated by Django 5.0.4 on 2024-04-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_foodhubuser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foodhubuser',
            managers=[
            ],
        ),
    ]
